// File: compiler/src/backends/r/mod.rs
//! R codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone R script
//! that replays the instructions on two stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct RBackend;

impl Backend<CompiledModule> for RBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin R script
        let mut code = String::new();
        code.push_str("# Generated by T-Lang R backend\n");
        code.push_str("intStack <- c()\n");
        code.push_str("strStack <- c()\n\n");

        // 3. Replay each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("intStack <- c(intStack, {})\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("strStack <- c(strStack, \"{}\")\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "if (length(strStack) > 0) {\n\
                     \tcat(tail(strStack, 1), sep = \"\")\n\
                     \tstrStack <- head(strStack, -1)\n\
                     } else if (length(intStack) > 0) {\n\
                     \tcat(tail(intStack, 1), sep = \"\")\n\
                     \tintStack <- head(intStack, -1)\n\
                     }\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End of script
        code.push('\n');
        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "r"
    }
}

// Register this backend at startup
static R_REG: Lazy<()> = Lazy::new(|| {
    register_backend(RBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_R_REG: fn() = {
    fn init() {
        Lazy::force(&R_REG);
    }
    init
};
