// File: compiler/src/backends/powershell/mod.rs
//! PowerShell codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone PowerShell script
//! that replays the instructions on two simple stacks and writes output.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct PowershellBackend;

impl Backend<CompiledModule> for PowershellBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin PowerShell script
        let mut code = String::new();
        code.push_str("# Generated by T-Lang PowerShell backend\n");
        code.push_str("$intStack = @()\n");
        code.push_str("$strStack = @()\n\n");

        // 3. Translate each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }

            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!(
                    "$intStack += {0}\n",
                    n
                ));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('`', "``").replace('"', "`\"");
                code.push_str(&format!(
                    "$strStack += \"{}\"\n",
                    esc
                ));
            } else if instr == "CallPrint" {
                code.push_str(
                    r#"
if ($strStack.Count -gt 0) {
    $val = $strStack[-1]
    Write-Host -NoNewline $val
    $strStack = $strStack[0..($strStack.Count - 2)]
} elseif ($intStack.Count -gt 0) {
    $val = $intStack[-1]
    Write-Host -NoNewline $val
    $intStack = $intStack[0..($intStack.Count - 2)]
}
"#,
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End of script
        code.push('\n');
        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "powershell"
    }
}

// Register this backend at startup
static PS_REG: Lazy<()> = Lazy::new(|| {
    register_backend(PowershellBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_PS_REG: fn() = {
    fn init() {
        Lazy::force(&PS_REG);
    }
    init
};
