// File: compiler/src/backends/typescript/mod.rs
//! TypeScript codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone TypeScript script
//! that replays the instructions on two stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct TypescriptBackend;

impl Backend<CompiledModule> for TypescriptBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin TypeScript source
        let mut code = String::new();
        code.push_str("// Generated by T-Lang TypeScript backend\n");
        code.push_str("const intStack: number[] = [];\n");
        code.push_str("const strStack: string[] = [];\n\n");

        // 3. Replay each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("intStack.push({});\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("strStack.push(\"{}\");\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "if (strStack.length > 0) {\n\
                     \tprocess.stdout.write(strStack.pop()!);\n\
                     } else if (intStack.length > 0) {\n\
                     \tprocess.stdout.write(intStack.pop()!.toString());\n\
                     }\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End of script
        code.push_str("\n");
        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "typescript"
    }
}

// Register this backend at startup
static TS_REG: Lazy<()> = Lazy::new(|| {
    register_backend(TypescriptBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_TS_REG: fn() = {
    fn init() {
        Lazy::force(&TS_REG);
    }
    init
};
