// File: compiler/src/backends/swift/mod.rs
//! Swift codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone Swift script
//! that replays the instructions on two stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct SwiftBackend;

impl Backend<CompiledModule> for SwiftBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin Swift source
        let mut code = String::new();
        code.push_str("// Generated by T-Lang Swift backend\n");
        code.push_str("import Foundation\n\n");
        code.push_str("var intStack: [Int] = []\n");
        code.push_str("var strStack: [String] = []\n\n");
        code.push_str("func main() {\n");

        // 3. Replay each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }

            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("    intStack.append({})\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("    strStack.append(\"{}\")\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "    if let s = strStack.popLast() {\n\
                     \n        print(s, terminator: \"\")\n\
                     \n    } else if let i = intStack.popLast() {\n\
                     \n        print(i, terminator: \"\")\n\
                     \n    }\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End main
        code.push_str("}\n\n");
        code.push_str("main()\n");

        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "swift"
    }
}

// Register this backend at startup
static SWIFT_REG: Lazy<()> = Lazy::new(|| {
    register_backend(SwiftBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_SWIFT_REG: fn() = {
    fn init() {
        Lazy::force(&SWIFT_REG);
    }
    init
};
