// File: compiler/src/backends/go/mod.rs
//! Go codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone Go program
//! that replays the instructions on two simple stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct GoBackend;

impl Backend<CompiledModule> for GoBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin Go source
        let mut code = String::new();
        code.push_str("// Generated by T-Lang Go backend\n");
        code.push_str("package main\n\n");
        code.push_str("import (\n\t\"fmt\"\n)\n\n");
        code.push_str("func main() {\n");
        code.push_str("\tvar intStack []int64\n");
        code.push_str("\tvar strStack []string\n\n");

        // 3. Translate each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("\tintStack = append(intStack, {})\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!(
                    "\tstrStack = append(strStack, \"{}\")\n",
                    esc
                ));
            } else if instr == "CallPrint" {
                code.push_str(
                    "\tif len(strStack) > 0 {\n\
                     \t\tfmt.Print(strStack[len(strStack)-1])\n\
                     \t\tstrStack = strStack[:len(strStack)-1]\n\
                     \t} else if len(intStack) > 0 {\n\
                     \t\tfmt.Print(intStack[len(intStack)-1])\n\
                     \t\tintStack = intStack[:len(intStack)-1]\n\
                     \t}\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. Close main
        code.push_str("}\n");

        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "go"
    }
}

// Register this backend at startup
static GO_REG: Lazy<()> = Lazy::new(|| {
    register_backend(GoBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_GO_REG: fn() = {
    fn init() {
        Lazy::force(&GO_REG);
    }
    init
};
