// File: compiler/src/backends/rust/mod.rs
//! Rust codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone Rust program
//! that replays the instructions on two Vec-based stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct RustBackend;

impl Backend<CompiledModule> for RustBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin Rust source
        let mut code = String::new();
        code.push_str("// Generated by T-Lang Rust backend\n");
        code.push_str("fn main() {\n");
        code.push_str("    let mut int_stack: Vec<i64> = Vec::new();\n");
        code.push_str("    let mut str_stack: Vec<String> = Vec::new();\n\n");

        // 3. Translate each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("    int_stack.push({});\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("    str_stack.push(String::from(\"{}\"));\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "    if let Some(s) = str_stack.pop() {\n\
                     \n        print!(\"{}\", s);\n\
                     \n    } else if let Some(i) = int_stack.pop() {\n\
                     \n        print!(\"{}\", i);\n\
                     \n    }\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End of main
        code.push_str("}\n");

        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "rust"
    }
}

// Register this backend at startup
static RUST_REG: Lazy<()> = Lazy::new(|| {
    register_backend(RustBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_RUST_REG: fn() = {
    fn init() {
        Lazy::force(&RUST_REG);
    }
    init
};
