// File: compiler/src/backends/scheme/mod.rs
//! Scheme codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone Scheme script
//! that replays the instructions on a simple list-based stack and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct SchemeBackend;

impl Backend<CompiledModule> for SchemeBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin Scheme script
        let mut code = String::new();
        code.push_str(";;; Generated by T-Lang Scheme backend\n");
        code.push_str("(define int-stack '())\n");
        code.push_str("(define str-stack '())\n\n");
        code.push_str("(define (main)\n");

        // 3. Replay each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("  (set! int-stack (cons {} int-stack))\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("  (set! str-stack (cons \"{}\" str-stack))\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "  (if (not (null? str-stack))\n\
                     \n    (begin\n\
                     \n      (display (car str-stack))\n\
                     \n      (set! str-stack (cdr str-stack)))\n\
                     \n    (when (not (null? int-stack))\n\
                     \n      (display (car int-stack))\n\
                     \n      (set! int-stack (cdr int-stack))))\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End main and invoke
        code.push_str(")\n\n(main)\n");

        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "scheme"
    }
}

// Register this backend at startup
static SCHEME_REG: Lazy<()> = Lazy::new(|| {
    register_backend(SchemeBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_SCHEME_REG: fn() = {
    fn init() {
        Lazy::force(&SCHEME_REG);
    }
    init
};
