// File: compiler/src/backends/kotlin/mod.rs
//! Kotlin codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone Kotlin program
//! that replays the instructions on two stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct KotlinBackend;

impl Backend<CompiledModule> for KotlinBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin Kotlin source
        let mut code = String::new();
        code.push_str("// Generated by T-Lang Kotlin backend\n");
        code.push_str("fun main() {\n");
        code.push_str("    val intStack = mutableListOf<Long>()\n");
        code.push_str("    val strStack = mutableListOf<String>()\n\n");

        // 3. Translate each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("    intStack.add({})\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("    strStack.add(\"{}\")\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "    if (strStack.isNotEmpty()) {\n\
                     \n        print(strStack.removeAt(strStack.size - 1))\n\
                     \n    } else if (intStack.isNotEmpty()) {\n\
                     \n        print(intStack.removeAt(intStack.size - 1))\n\
                     \n    }\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. Close main
        code.push_str("}\n");

        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "kotlin"
    }
}

// Register this backend at startup
static KOTLIN_REG: Lazy<()> = Lazy::new(|| {
    register_backend(KotlinBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_KOTLIN_REG: fn() = {
    fn init() {
        Lazy::force(&KOTLIN_REG);
    }
    init
};
