// File: compiler/src/backends/ocaml/mod.rs
//! OCaml codegen backend for T-Lang.
//! Reads our IR debug-text and emits a standalone OCaml script
//! that replays the instructions on two stacks and prints values.

use plugin_api::{register_backend, Backend, CompiledModule, BackendError};
use once_cell::sync::Lazy;
use std::{any::Any, str};

#[derive(Debug)]
pub struct OcamlBackend;

impl Backend<CompiledModule> for OcamlBackend {
    type ModuleIr = Box<dyn Any + Send + Sync>;

    fn compile(&self, module: CompiledModule) -> Result<Self::ModuleIr, BackendError> {
        // 1. Decode IR text
        let ir = str::from_utf8(&module.bytecode)
            .map_err(|e| BackendError::Generic(format!("Invalid UTF-8 IR: {}", e)))?;

        // 2. Begin OCaml script
        let mut code = String::new();
        code.push_str("(* Generated by T-Lang OCaml backend *)\n");
        code.push_str("let () =\n");
        code.push_str("  let int_stack = Stack.create () in\n");
        code.push_str("  let str_stack = Stack.create () in\n\n");

        // 3. Replay each IR instruction
        for line in ir.lines() {
            let instr = line.trim();
            if instr.is_empty() || instr == "Nop" {
                continue;
            }
            if let Some(n) = instr.strip_prefix("PushInt(").and_then(|s| s.strip_suffix(")")) {
                code.push_str(&format!("  Stack.push (int_of_string \"{}\") int_stack;\n", n));
            } else if let Some(raw) = instr
                .strip_prefix("PushStr(\"")
                .and_then(|s| s.strip_suffix("\")"))
            {
                let esc = raw.replace('\\', "\\\\").replace('"', "\\\"");
                code.push_str(&format!("  Stack.push \"{}\" str_stack;\n", esc));
            } else if instr == "CallPrint" {
                code.push_str(
                    "  if not (Stack.is_empty str_stack) then begin\n\
                     \n    print_string (Stack.pop str_stack);\n\
                     \n  end else if not (Stack.is_empty int_stack) then begin\n\
                     \n    print_int (Stack.pop int_stack);\n\
                     \n  end;\n",
                );
            } else {
                return Err(BackendError::Generic(format!("Unknown IR instr: {}", instr)));
            }
        }

        // 4. End program
        code.push_str("  ();;\n");

        Ok(Box::new(code.into_bytes()))
    }

    fn name(&self) -> &'static str {
        "ocaml"
    }
}

// Register this backend at startup
static OCAML_REG: Lazy<()> = Lazy::new(|| {
    register_backend(OcamlBackend);
});

#[doc(hidden)]
#[allow(non_upper_case_globals)]
#[used]
static FORCE_OCAML_REG: fn() = {
    fn init() {
        Lazy::force(&OCAML_REG);
    }
    init
};
